language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libleveldb-dev
install:
  - pip install -r requirements-dev.txt
  - make cython
  - pip install .
script:
  - make test
